print "hello"

raise Exception("failed")

print "hello"

raise Exception("failed")

